name: Data Refresh - Python (Docker)

on:
  schedule:
    - cron: "0 */1 * * *"
jobs:
  refresh-the-dashboard:
    runs-on: ubuntu-22.04
    container:
      image: docker.io/rkrispin/eia_data_refresh:arm64.0.0.0.9003
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
        with:
          ref: "stg"
      - name: Data Refresh
        run: bash ./python/data_refresh_py.sh "RamiKrispin" "ramkrisp@umich.edu"
        env:
          API_KEY: ${{ secrets.EIA_API_KEY }}
